baseURL: https://ziqi-website.netlify.app/
languageCode: en-us
title: Portfolio website for Ziqi
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A DOER WHO ASPIRES TO SHINE IN THE FINANCE WORLD
      
    title: Hi there, it's Ziqi
  blog: {}
  contact:
    address:
     - city: London
       country: United Kingdom
       street: Regents Park
       title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ziqi.gz@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 7848859506
        title: Phone
  custom_css: []
  custom_js: []
  description: Student at London Business School
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Ziqi Li
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
  #      url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Zi-qi
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ziqi-li-0b7012173/
  image: Ziqi_background_photo.jpg
  name: Ziqi Li
  navigation:
    button1:
      - name: Get Started
      # url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Professional Resume
        url: blogs/CV_Ziqi_Li_copy.pdf
      - name: Dissertation
        url: blogs/magna
      - name: Case Study
        url: blogs/airbnb
      - name: Stock Analysis
        url: blogs/risk_return
      - name: Stock Pitch
        url: blogs/ipsum
      - name: Travel Blogs
        url: https://manchesterontheroad.com/2020/08/13/chapter-three-places-to-visit-in-canberra/
    menu: Menu
    subtitle: LBS MFA2022
    title: Ziqi Li
  tiles:
    enable: yes
    showcase:
      - image: Ziqi's Photo.jpg
        subtitle: PROFESSIONAL RESUME
        title: Ziqi's CV
        url: blogs/CV_Ziqi_Li_copy.pdf
      - image: Ziqi-essay.jpg
        subtitle: ZIQI’S BACHELOR DISSERTATION
        title: An Empirical Study of German American Bancorp’s Acquisition of River Valley Bancorp
        url: blogs/magna
      - image: airbnb.jpg
        subtitle: WHAT FACTORS AFFECT YOUR COST OF STAY?
        title: Price modelling for Airbnb in Amsterdam
        url: blogs/airbnb.html
      - image: stock_photo.jpg
        subtitle: STOCK ANALYSIS FOR DJIA
        title: Risk Return of DJIA Industrial Average
        url: blogs/risk_return
      - image: burberry.jpg
        subtitle: SHOULD I BUY NOW?
        title: A Stock Pitch for Burberry
        url: blogs/ipsum
      - image: exchange_photo.jpg
        subtitle: ZIQI’S TRAVEL JOURNAL IN AUSTRALIA
        title: Manchester on the Road
        url: https://manchesterontheroad.com/2020/08/13/chapter-three-places-to-visit-in-canberra/
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "A student at London Business School, a brainstormer for corporation, a trusted partner to colleagues, a confidant to friends
I'm a dreamer and a doer, who wants to break into the finance industry and travel the world."
    title: ABOUT ME
    url: blogs
