baseURL: https://ziqi-website.netlify.app/
languageCode: en-us
title: Portfolio website for Ziqi
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Student at London Business School
    title: Hi, this is Ziqi
  blog: {}
  contact:+44 7848859506
    address:
    Regent's Park
    London 
    United Kingdom
    NW1 4SA
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ziqi.gz@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 7848859506
        title: Phone
  custom_css: []
  custom_js: []
  description: Student at London Business School
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Ziqi Li
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
  #      url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Zi-qi
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ziqi-li-0b7012173/
  image: Ziqi's background photo.jpg
  name: Ziqi Li
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Ziqi's Photo.jpg
        subtitle: PROFESSIONAL RESUME
        title: Ziqi's CV
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Risk Return of DJIA Industrial Average
        url: blogs/risk_return
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
